DROP SCHEMA IF EXISTS studentDB;
CREATE SCHEMA studentDB;

DROP USER IF EXISTS myUser;
CREATE USER myUser WITH PASSWORD 'myPass' SUPERUSER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA studentDB TO myUser;
